# Source: https://grantwritingandfunding.com/banned-and-trigger-words-in-federal-grant-writing-in-the-trump-administration-2-0/ 
[
    "activism",
    "activists",
    "advocacy",
    "advocate",
    "barrier",
    "barriers",
    "biased",
    "bias",
    "BIPOC",
    "Black and Latinx",
    "community diversity",
    "community equity",
    "cultural differences",
    "cultural heritage",
    "culturally responsive",
    "disabilities",
    "discrimination",
    "discriminatory",
    "backgrounds",
    "groups",
    "diversified",
    "diversify",
    "enhancing",
    "equal opportunity",
    "equality",
    "equitable",
    "ethnicity",
    "excluded",
    "female",
    "fostering",
    "gender",
    "hate speech",
    "Hispanic minority",
    "historically",
    "implicit bias",
    "inclusion",
    "inclusive",
    "increase",
    "indigenous community",
    "inequalities",
    "inequities",
    "institutional",
    "LGBTQ",
    "marginalize",
    "minorities",
    "multicultural",
    "polarization",
    "political",
    "prejudice",
    "privileges",
    "promoting",
    "race",
    "racial",
    "justice",
    "sense of belonging",
    "sexual preferences",
    "social justice",
    "sociocultural",
    "socioeconomic",
    "status",
    "stereotypes",
    "systemic",
    "trauma",
    "underappreciated",
    "underrepresented",
    "underserved",
    "victim",
    "women"
]